fixes

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -70,6 +70,18 @@ tasks:
     upgrade:
         cmds:
             - go tool go-mod-upgrade
+    sonar:
+        vars:
+            SONAR_HOST: https://sonarqube.tooling.dp.iskaypet.com
+        cmds:
+            - |
+                if [ -z "$SONAR_TOKEN" ]; then
+                  echo "Error: SONAR_TOKEN is not set."
+                  exit 1
+                fi
+                GOEXPERIMENT=nocoverageredesign go test -coverprofile=coverage.out ./... || true
+                go tool golangci-lint run --fix || true
+                sonar-scanner -Dsonar.host.url={{.SONAR_HOST}}
     default:
         cmds:
             -   task: download
